# Travis-CI Build for ltr++ library

language: node_js
node_js:
  - "10"

branches:
  only:
    - main
    - develop

install:
  - yarn install
  - yarn add codecov --dev

script:
  - yarn test
  - yarn jest --collect-coverage

after_success: 
  - codecov --disable=gcov -f ./coverage/lcov.info