# Travis-CI Build for ltr++ library

language: node_js
node_js:
  - "10"

branches:
  only:
    - master
    - develop

install:
  - yarn install
  - yarn add codecov --dev

script:
  - yarn test && codecov